global:

# templates:
# - /etc/alertmanager/template/*.tmpl

# The root route on which each incoming alert enters.
route:
  receiver: alertreceiver

  # The child route trees. Not used at the moment.
  routes:

receivers:
- name: alertreceiver
  webhook_configs:
    - url: "http://"
